# Generated by Django 2.2.6 on 2019-10-23 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phone', models.TextField(max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=100)),
                ('gps_coordinates', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DrinkProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('size', models.TextField(max_length=100)),
                ('price', models.FloatField()),
                ('public_product_id', models.IntegerField()),
                ('contains_caffeine', models.BooleanField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('calories', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sugar_content', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('type', models.TextField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('size', models.TextField(max_length=100)),
                ('price', models.FloatField()),
                ('public_product_id', models.IntegerField()),
                ('vegan', models.BooleanField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vegetarian', models.BooleanField()),
                ('gluten_free', models.BooleanField()),
                ('user_created', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('expected_giving_to_courier_date', models.DateTimeField()),
                ('status', models.TextField(max_length=30)),
                ('given_to_courier_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=300)),
                ('discount', models.FloatField()),
                ('expected_delivery_date', models.DateTimeField()),
                ('Courier_Orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Courier')),
                ('O_T_M_User_Orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('photo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PriviligeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('grants_access_to', models.TextField(max_length=100)),
                ('M_T_M_Priviligies_Emails2', models.ManyToManyField(to='app.EmailTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email_token', models.TextField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('M_T_O_PriviligeLevel_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PriviligeLevel')),
            ],
        ),
        migrations.CreateModel(
            name='UserPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname', models.TextField(max_length=50)),
                ('O_T_O_FoodProduct_UserPizza', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.FoodProduct')),
                ('O_T_O_User_UserPizza', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.TextField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('was_payback', models.BooleanField()),
                ('payment_option', models.TextField(max_length=100)),
                ('amount', models.FloatField()),
                ('currency', models.TextField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('O_T_O_Order_Transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('O_T_M_Order_OrderItems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Order')),
                ('O_T_M_Product_OrderItems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DrinkProduct')),
                ('O_T_M_Product_OrderItems2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FoodProduct')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='O_T_O_Transaction_Order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Transaction'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_amount_in_inventory', models.FloatField()),
                ('fats_per_serving', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('price_per_serving', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_topping', models.BooleanField()),
                ('protein_per_serving', models.FloatField()),
                ('is_allergen', models.BooleanField()),
                ('carbs_per_serving', models.FloatField()),
                ('dairy_free', models.BooleanField()),
                ('vegan', models.BooleanField()),
                ('FoodProduct_To_Ingredient', models.ManyToManyField(to='app.FoodProduct')),
            ],
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='FoodProduct_To_Ingredient_2',
            field=models.ManyToManyField(to='app.Ingredient'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='M_T_M_Priviliges_Emails',
            field=models.ManyToManyField(to='app.PriviligeLevel'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('address_type', models.TextField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('door_number_and_others', models.TextField(max_length=200)),
                ('city', models.TextField(max_length=100)),
                ('zip_code', models.TextField(max_length=20)),
                ('street_and_street_number', models.TextField(max_length=200)),
                ('O_T_M_User_Adresses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
