# Generated by Django 2.2.7 on 2019-11-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodproduct',
            name='FoodProduct_To_Ingredient_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='O_T_O_Transaction_Order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='M_T_M_Product_OrderItems',
            field=models.ManyToManyField(related_name='orderitems', to='app.DrinkProduct'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='M_T_M_Product_OrderItems2',
            field=models.ManyToManyField(related_name='orderitems', to='app.FoodProduct'),
        ),
    ]
