# Generated by Django 2.2.7 on 2019-11-09 13:44

from django.db import models, migrations
import django.db.models.deletion


def make_many_relationships(apps, schema_editor):
    OrderItem = apps.get_model('app', 'OrderItem')

    for oi in OrderItem.objects.all():
        oi.M_T_M_Product_OrderItems2.add(oi.O_T_M_Product_OrderItems2)
        oi.M_T_M_Product_OrderItems.add(oi.O_T_M_Product_OrderItems)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191109_1342'),
    ]

    operations = [
        migrations.RunPython(make_many_relationships),
    ]