# Generated by Django 2.2.7 on 2019-11-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191109_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='O_T_M_Product_OrderItems',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='O_T_M_Product_OrderItems2',
        ),
    ]
