# Generated by Django 2.2.7 on 2019-11-09 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191109_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='O_T_O_Address_Order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Address'),
        ),
    ]
